// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1() {
    driver.get("http://localhost/addressbook/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.name("user")).sendKeys("admin");
    driver.findElement(By.name("pass")).sendKeys("secret");
    driver.findElement(By.name("pass")).sendKeys(Keys.ENTER);
    driver.findElement(By.linkText("add new")).click();
    driver.findElement(By.name("firstname")).click();
    driver.findElement(By.name("firstname")).sendKeys("first_name");
    driver.findElement(By.name("middlename")).sendKeys("middle_name");
    driver.findElement(By.name("lastname")).sendKeys("last_name");
    driver.findElement(By.name("nickname")).sendKeys("nickname");
    driver.findElement(By.name("title")).click();
    driver.findElement(By.name("title")).sendKeys("title");
    driver.findElement(By.name("company")).sendKeys("company");
    driver.findElement(By.name("address")).sendKeys("address");
    driver.findElement(By.name("home")).sendKeys("home");
    driver.findElement(By.name("mobile")).sendKeys("mobile");
    driver.findElement(By.name("work")).sendKeys("work");
    driver.findElement(By.name("fax")).sendKeys("fax");
    driver.findElement(By.name("email")).sendKeys("email");
    driver.findElement(By.name("email2")).sendKeys("email2");
    driver.findElement(By.name("email3")).sendKeys("email3");
    driver.findElement(By.name("homepage")).sendKeys("homepage");
    driver.findElement(By.name("bday")).click();
    {
      WebElement dropdown = driver.findElement(By.name("bday"));
      dropdown.findElement(By.xpath("//option[. = '1']")).click();
    }
    driver.findElement(By.name("bmonth")).click();
    {
      WebElement dropdown = driver.findElement(By.name("bmonth"));
      dropdown.findElement(By.xpath("//option[. = 'March']")).click();
    }
    driver.findElement(By.name("byear")).click();
    driver.findElement(By.name("byear")).sendKeys("2000");
    driver.findElement(By.name("aday")).click();
    {
      WebElement dropdown = driver.findElement(By.name("aday"));
      dropdown.findElement(By.xpath("//option[. = '10']")).click();
    }
    driver.findElement(By.name("amonth")).click();
    {
      WebElement dropdown = driver.findElement(By.name("amonth"));
      dropdown.findElement(By.xpath("//option[. = 'November']")).click();
    }
    driver.findElement(By.name("ayear")).click();
    driver.findElement(By.name("ayear")).sendKeys("2005");
    driver.findElement(By.name("new_group")).click();
    driver.findElement(By.xpath("(//input[@name=\'submit\'])[2]")).click();
    driver.findElement(By.linkText("home page")).click();
    driver.findElement(By.linkText("Logout")).click();
  }
}
